// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module axi_tmu_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 5
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output axi_tmu_reg_pkg::axi_tmu_reg2hw_t reg2hw, // Write
  input  axi_tmu_reg_pkg::axi_tmu_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import axi_tmu_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [7:0] budget_avld_ardy_wd;
  logic budget_avld_ardy_we;
  logic [7:0] budget_w_liveness_wd;
  logic budget_w_liveness_we;
  logic [7:0] budget_b_wd;
  logic budget_b_we;
  logic [7:0] budget_r_liveness_wd;
  logic budget_r_liveness_we;
  logic reset_qs;
  logic fault_log_fault_valid_qs;
  logic fault_log_fault_valid_wd;
  logic fault_log_fault_valid_we;
  logic [2:0] fault_log_fault_type_qs;
  logic [2:0] fault_log_fault_type_wd;
  logic fault_log_fault_type_we;
  logic fault_log_fault_dir_qs;
  logic fault_log_fault_dir_wd;
  logic fault_log_fault_dir_we;
  logic [3:0] fault_log_fault_phase_qs;
  logic [3:0] fault_log_fault_phase_wd;
  logic fault_log_fault_phase_we;
  logic [15:0] fault_log_fault_id_qs;
  logic [15:0] fault_log_fault_id_wd;
  logic fault_log_fault_id_we;

  // Register instances
  // R[budget_avld_ardy]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_avld_ardy (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_avld_ardy_we),
    .wd     (budget_avld_ardy_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_avld_ardy.q ),

    .qs     ()
  );


  // R[budget_w_liveness]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_w_liveness (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_w_liveness_we),
    .wd     (budget_w_liveness_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_w_liveness.q ),

    .qs     ()
  );


  // R[budget_b]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_b (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_b_we),
    .wd     (budget_b_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_b.q ),

    .qs     ()
  );


  // R[budget_r_liveness]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_r_liveness (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_r_liveness_we),
    .wd     (budget_r_liveness_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_r_liveness.q ),

    .qs     ()
  );


  // R[reset]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_reset (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.reset.de),
    .d      (hw2reg.reset.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (reset_qs)
  );


  // R[fault_log]: V(False)

  //   F[fault_valid]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_fault_log_fault_valid (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fault_log_fault_valid_we),
    .wd     (fault_log_fault_valid_wd),

    // from internal hardware
    .de     (hw2reg.fault_log.fault_valid.de),
    .d      (hw2reg.fault_log.fault_valid.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fault_log.fault_valid.q ),

    // to register interface (read)
    .qs     (fault_log_fault_valid_qs)
  );


  //   F[fault_type]: 3:1
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RW"),
    .RESVAL  (3'h0)
  ) u_fault_log_fault_type (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fault_log_fault_type_we),
    .wd     (fault_log_fault_type_wd),

    // from internal hardware
    .de     (hw2reg.fault_log.fault_type.de),
    .d      (hw2reg.fault_log.fault_type.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fault_log.fault_type.q ),

    // to register interface (read)
    .qs     (fault_log_fault_type_qs)
  );


  //   F[fault_dir]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_fault_log_fault_dir (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fault_log_fault_dir_we),
    .wd     (fault_log_fault_dir_wd),

    // from internal hardware
    .de     (hw2reg.fault_log.fault_dir.de),
    .d      (hw2reg.fault_log.fault_dir.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fault_log.fault_dir.q ),

    // to register interface (read)
    .qs     (fault_log_fault_dir_qs)
  );


  //   F[fault_phase]: 8:5
  prim_subreg #(
    .DW      (4),
    .SWACCESS("RW"),
    .RESVAL  (4'h0)
  ) u_fault_log_fault_phase (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fault_log_fault_phase_we),
    .wd     (fault_log_fault_phase_wd),

    // from internal hardware
    .de     (hw2reg.fault_log.fault_phase.de),
    .d      (hw2reg.fault_log.fault_phase.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fault_log.fault_phase.q ),

    // to register interface (read)
    .qs     (fault_log_fault_phase_qs)
  );


  //   F[fault_id]: 24:9
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_fault_log_fault_id (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fault_log_fault_id_we),
    .wd     (fault_log_fault_id_wd),

    // from internal hardware
    .de     (hw2reg.fault_log.fault_id.de),
    .d      (hw2reg.fault_log.fault_id.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fault_log.fault_id.q ),

    // to register interface (read)
    .qs     (fault_log_fault_id_qs)
  );




  logic [5:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == AXI_TMU_BUDGET_AVLD_ARDY_OFFSET);
    addr_hit[1] = (reg_addr == AXI_TMU_BUDGET_W_LIVENESS_OFFSET);
    addr_hit[2] = (reg_addr == AXI_TMU_BUDGET_B_OFFSET);
    addr_hit[3] = (reg_addr == AXI_TMU_BUDGET_R_LIVENESS_OFFSET);
    addr_hit[4] = (reg_addr == AXI_TMU_RESET_OFFSET);
    addr_hit[5] = (reg_addr == AXI_TMU_FAULT_LOG_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(AXI_TMU_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(AXI_TMU_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(AXI_TMU_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(AXI_TMU_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(AXI_TMU_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(AXI_TMU_PERMIT[5] & ~reg_be)))));
  end

  assign budget_avld_ardy_we = addr_hit[0] & reg_we & !reg_error;
  assign budget_avld_ardy_wd = reg_wdata[7:0];

  assign budget_w_liveness_we = addr_hit[1] & reg_we & !reg_error;
  assign budget_w_liveness_wd = reg_wdata[7:0];

  assign budget_b_we = addr_hit[2] & reg_we & !reg_error;
  assign budget_b_wd = reg_wdata[7:0];

  assign budget_r_liveness_we = addr_hit[3] & reg_we & !reg_error;
  assign budget_r_liveness_wd = reg_wdata[7:0];

  assign fault_log_fault_valid_we = addr_hit[5] & reg_we & !reg_error;
  assign fault_log_fault_valid_wd = reg_wdata[0];

  assign fault_log_fault_type_we = addr_hit[5] & reg_we & !reg_error;
  assign fault_log_fault_type_wd = reg_wdata[3:1];

  assign fault_log_fault_dir_we = addr_hit[5] & reg_we & !reg_error;
  assign fault_log_fault_dir_wd = reg_wdata[4];

  assign fault_log_fault_phase_we = addr_hit[5] & reg_we & !reg_error;
  assign fault_log_fault_phase_wd = reg_wdata[8:5];

  assign fault_log_fault_id_we = addr_hit[5] & reg_we & !reg_error;
  assign fault_log_fault_id_wd = reg_wdata[24:9];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[1]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[2]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[3]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[4]: begin
        reg_rdata_next[0] = reset_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[0] = fault_log_fault_valid_qs;
        reg_rdata_next[3:1] = fault_log_fault_type_qs;
        reg_rdata_next[4] = fault_log_fault_dir_qs;
        reg_rdata_next[8:5] = fault_log_fault_phase_qs;
        reg_rdata_next[24:9] = fault_log_fault_id_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module axi_tmu_reg_top_intf
#(
  parameter int AW = 5,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output axi_tmu_reg_pkg::axi_tmu_reg2hw_t reg2hw, // Write
  input  axi_tmu_reg_pkg::axi_tmu_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  axi_tmu_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


