// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package axi_tmu_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_avld_ardy_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_b2b_reg_t;

  typedef struct packed {
    logic [11:0] q;
  } axi_tmu_reg2hw_budget_r2r_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } fault_valid;
    struct packed {
      logic [2:0]  q;
    } fault_type;
    struct packed {
      logic        q;
    } fault_dir;
    struct packed {
      logic [3:0]  q;
    } fault_phase;
    struct packed {
      logic [15:0] q;
    } fault_id;
  } axi_tmu_reg2hw_fault_log_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } axi_tmu_hw2reg_reset_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } fault_valid;
    struct packed {
      logic [2:0]  d;
      logic        de;
    } fault_type;
    struct packed {
      logic        d;
      logic        de;
    } fault_dir;
    struct packed {
      logic [3:0]  d;
      logic        de;
    } fault_phase;
    struct packed {
      logic [15:0] d;
      logic        de;
    } fault_id;
  } axi_tmu_hw2reg_fault_log_reg_t;

  // Register -> HW type
  typedef struct packed {
    axi_tmu_reg2hw_budget_avld_ardy_reg_t budget_avld_ardy; // [52:45]
    axi_tmu_reg2hw_budget_b2b_reg_t budget_b2b; // [44:37]
    axi_tmu_reg2hw_budget_r2r_reg_t budget_r2r; // [36:25]
    axi_tmu_reg2hw_fault_log_reg_t fault_log; // [24:0]
  } axi_tmu_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    axi_tmu_hw2reg_reset_reg_t reset; // [31:30]
    axi_tmu_hw2reg_fault_log_reg_t fault_log; // [29:0]
  } axi_tmu_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_AVLD_ARDY_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_B2B_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_R2R_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] AXI_TMU_RESET_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] AXI_TMU_FAULT_LOG_OFFSET = 5'h 10;

  // Register index
  typedef enum int {
    AXI_TMU_BUDGET_AVLD_ARDY,
    AXI_TMU_BUDGET_B2B,
    AXI_TMU_BUDGET_R2R,
    AXI_TMU_RESET,
    AXI_TMU_FAULT_LOG
  } axi_tmu_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] AXI_TMU_PERMIT [5] = '{
    4'b 0001, // index[0] AXI_TMU_BUDGET_AVLD_ARDY
    4'b 0001, // index[1] AXI_TMU_BUDGET_B2B
    4'b 0011, // index[2] AXI_TMU_BUDGET_R2R
    4'b 0001, // index[3] AXI_TMU_RESET
    4'b 1111  // index[4] AXI_TMU_FAULT_LOG
  };

endpackage

