// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package axi_tmu_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 7;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_awvld_awrdy_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_awhs_wfirst_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_wvld_wrdy_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_w_liveness_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_wlast_bvld_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_bvld_brdy_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_arvld_arrdy_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_rvld_rrdy_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_arhs_rfirst_reg_t;

  typedef struct packed {
    logic [7:0]  q;
  } axi_tmu_reg2hw_budget_r_liveness_reg_t;

  typedef struct packed {
    logic        q;
  } axi_tmu_reg2hw_reset_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } fault_valid;
    struct packed {
      logic [2:0]  q;
    } fault_type;
    struct packed {
      logic        q;
    } fault_dir;
    struct packed {
      logic [3:0]  q;
    } fault_phase;
    struct packed {
      logic [15:0] q;
    } fault_id;
  } axi_tmu_reg2hw_fault_log_reg_t;

  typedef struct packed {
    logic [9:0] q;
  } axi_tmu_reg2hw_latency_awvld_wfirst_reg_t;

  typedef struct packed {
    logic [9:0] q;
  } axi_tmu_reg2hw_latency_wvld_wrdy_reg_t;

  typedef struct packed {
    logic [9:0] q;
  } axi_tmu_reg2hw_latency_wvld_wlast_reg_t;

  typedef struct packed {
    logic [9:0] q;
  } axi_tmu_reg2hw_latency_wlast_bvld_reg_t;

  typedef struct packed {
    logic [9:0] q;
  } axi_tmu_reg2hw_latency_bvld_brdy_reg_t;

  typedef struct packed {
    logic [9:0] q;
  } axi_tmu_reg2hw_latency_arvld_arrdy_reg_t;

  typedef struct packed {
    logic [9:0] q;
  } axi_tmu_reg2hw_latency_arvld_rvld_reg_t;

  typedef struct packed {
    logic [9:0] q;
  } axi_tmu_reg2hw_latency_rvld_rrdy_reg_t;

  typedef struct packed {
    logic [9:0] q;
  } axi_tmu_reg2hw_latency_rvld_rlast_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } axi_tmu_hw2reg_reset_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } fault_valid;
    struct packed {
      logic [2:0]  d;
      logic        de;
    } fault_type;
    struct packed {
      logic        d;
      logic        de;
    } fault_dir;
    struct packed {
      logic [3:0]  d;
      logic        de;
    } fault_phase;
    struct packed {
      logic [15:0] d;
      logic        de;
    } fault_id;
  } axi_tmu_hw2reg_fault_log_reg_t;

  typedef struct packed {
    logic [9:0] d;
    logic        de;
  } axi_tmu_hw2reg_latency_awvld_wfirst_reg_t;

  typedef struct packed {
    logic [9:0] d;
    logic        de;
  } axi_tmu_hw2reg_latency_wvld_wrdy_reg_t;

  typedef struct packed {
    logic [9:0] d;
    logic        de;
  } axi_tmu_hw2reg_latency_wvld_wlast_reg_t;

  typedef struct packed {
    logic [9:0] d;
    logic        de;
  } axi_tmu_hw2reg_latency_wlast_bvld_reg_t;

  typedef struct packed {
    logic [9:0] d;
    logic        de;
  } axi_tmu_hw2reg_latency_bvld_brdy_reg_t;

  typedef struct packed {
    logic [9:0] d;
    logic        de;
  } axi_tmu_hw2reg_latency_arvld_arrdy_reg_t;

  typedef struct packed {
    logic [9:0] d;
    logic        de;
  } axi_tmu_hw2reg_latency_arvld_rvld_reg_t;

  typedef struct packed {
    logic [9:0] d;
    logic        de;
  } axi_tmu_hw2reg_latency_rvld_rrdy_reg_t;

  typedef struct packed {
    logic [9:0] d;
    logic        de;
  } axi_tmu_hw2reg_latency_rvld_rlast_reg_t;

  // Register -> HW type
  typedef struct packed {
    axi_tmu_reg2hw_budget_awvld_awrdy_reg_t budget_awvld_awrdy; // [195:188]
    axi_tmu_reg2hw_budget_awhs_wfirst_reg_t budget_awhs_wfirst; // [187:180]
    axi_tmu_reg2hw_budget_wvld_wrdy_reg_t budget_wvld_wrdy; // [179:172]
    axi_tmu_reg2hw_budget_w_liveness_reg_t budget_w_liveness; // [171:164]
    axi_tmu_reg2hw_budget_wlast_bvld_reg_t budget_wlast_bvld; // [163:156]
    axi_tmu_reg2hw_budget_bvld_brdy_reg_t budget_bvld_brdy; // [155:148]
    axi_tmu_reg2hw_budget_arvld_arrdy_reg_t budget_arvld_arrdy; // [147:140]
    axi_tmu_reg2hw_budget_rvld_rrdy_reg_t budget_rvld_rrdy; // [139:132]
    axi_tmu_reg2hw_budget_arhs_rfirst_reg_t budget_arhs_rfirst; // [131:124]
    axi_tmu_reg2hw_budget_r_liveness_reg_t budget_r_liveness; // [123:116]
    axi_tmu_reg2hw_reset_reg_t reset; // [115:115]
    axi_tmu_reg2hw_fault_log_reg_t fault_log; // [114:90]
    axi_tmu_reg2hw_latency_awvld_wfirst_reg_t latency_awvld_wfirst; // [89:80]
    axi_tmu_reg2hw_latency_wvld_wrdy_reg_t latency_wvld_wrdy; // [79:70]
    axi_tmu_reg2hw_latency_wvld_wlast_reg_t latency_wvld_wlast; // [69:60]
    axi_tmu_reg2hw_latency_wlast_bvld_reg_t latency_wlast_bvld; // [59:50]
    axi_tmu_reg2hw_latency_bvld_brdy_reg_t latency_bvld_brdy; // [49:40]
    axi_tmu_reg2hw_latency_arvld_arrdy_reg_t latency_arvld_arrdy; // [39:30]
    axi_tmu_reg2hw_latency_arvld_rvld_reg_t latency_arvld_rvld; // [29:20]
    axi_tmu_reg2hw_latency_rvld_rrdy_reg_t latency_rvld_rrdy; // [19:10]
    axi_tmu_reg2hw_latency_rvld_rlast_reg_t latency_rvld_rlast; // [9:0]
  } axi_tmu_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    axi_tmu_hw2reg_reset_reg_t reset; // [130:129]
    axi_tmu_hw2reg_fault_log_reg_t fault_log; // [128:99]
    axi_tmu_hw2reg_latency_awvld_wfirst_reg_t latency_awvld_wfirst; // [98:88]
    axi_tmu_hw2reg_latency_wvld_wrdy_reg_t latency_wvld_wrdy; // [87:77]
    axi_tmu_hw2reg_latency_wvld_wlast_reg_t latency_wvld_wlast; // [76:66]
    axi_tmu_hw2reg_latency_wlast_bvld_reg_t latency_wlast_bvld; // [65:55]
    axi_tmu_hw2reg_latency_bvld_brdy_reg_t latency_bvld_brdy; // [54:44]
    axi_tmu_hw2reg_latency_arvld_arrdy_reg_t latency_arvld_arrdy; // [43:33]
    axi_tmu_hw2reg_latency_arvld_rvld_reg_t latency_arvld_rvld; // [32:22]
    axi_tmu_hw2reg_latency_rvld_rrdy_reg_t latency_rvld_rrdy; // [21:11]
    axi_tmu_hw2reg_latency_rvld_rlast_reg_t latency_rvld_rlast; // [10:0]
  } axi_tmu_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_AWVLD_AWRDY_OFFSET = 7'h 0;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_AWHS_WFIRST_OFFSET = 7'h 4;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_WVLD_WRDY_OFFSET = 7'h 8;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_W_LIVENESS_OFFSET = 7'h c;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_WLAST_BVLD_OFFSET = 7'h 10;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_BVLD_BRDY_OFFSET = 7'h 14;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_ARVLD_ARRDY_OFFSET = 7'h 18;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_RVLD_RRDY_OFFSET = 7'h 1c;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_ARHS_RFIRST_OFFSET = 7'h 20;
  parameter logic [BlockAw-1:0] AXI_TMU_BUDGET_R_LIVENESS_OFFSET = 7'h 24;
  parameter logic [BlockAw-1:0] AXI_TMU_RESET_OFFSET = 7'h 28;
  parameter logic [BlockAw-1:0] AXI_TMU_FAULT_LOG_OFFSET = 7'h 2c;
  parameter logic [BlockAw-1:0] AXI_TMU_LATENCY_AWVLD_WFIRST_OFFSET = 7'h 30;
  parameter logic [BlockAw-1:0] AXI_TMU_LATENCY_WVLD_WRDY_OFFSET = 7'h 34;
  parameter logic [BlockAw-1:0] AXI_TMU_LATENCY_WVLD_WLAST_OFFSET = 7'h 38;
  parameter logic [BlockAw-1:0] AXI_TMU_LATENCY_WLAST_BVLD_OFFSET = 7'h 3c;
  parameter logic [BlockAw-1:0] AXI_TMU_LATENCY_BVLD_BRDY_OFFSET = 7'h 40;
  parameter logic [BlockAw-1:0] AXI_TMU_LATENCY_ARVLD_ARRDY_OFFSET = 7'h 44;
  parameter logic [BlockAw-1:0] AXI_TMU_LATENCY_ARVLD_RVLD_OFFSET = 7'h 48;
  parameter logic [BlockAw-1:0] AXI_TMU_LATENCY_RVLD_RRDY_OFFSET = 7'h 4c;
  parameter logic [BlockAw-1:0] AXI_TMU_LATENCY_RVLD_RLAST_OFFSET = 7'h 50;

  // Register index
  typedef enum int {
    AXI_TMU_BUDGET_AWVLD_AWRDY,
    AXI_TMU_BUDGET_AWHS_WFIRST,
    AXI_TMU_BUDGET_WVLD_WRDY,
    AXI_TMU_BUDGET_W_LIVENESS,
    AXI_TMU_BUDGET_WLAST_BVLD,
    AXI_TMU_BUDGET_BVLD_BRDY,
    AXI_TMU_BUDGET_ARVLD_ARRDY,
    AXI_TMU_BUDGET_RVLD_RRDY,
    AXI_TMU_BUDGET_ARHS_RFIRST,
    AXI_TMU_BUDGET_R_LIVENESS,
    AXI_TMU_RESET,
    AXI_TMU_FAULT_LOG,
    AXI_TMU_LATENCY_AWVLD_WFIRST,
    AXI_TMU_LATENCY_WVLD_WRDY,
    AXI_TMU_LATENCY_WVLD_WLAST,
    AXI_TMU_LATENCY_WLAST_BVLD,
    AXI_TMU_LATENCY_BVLD_BRDY,
    AXI_TMU_LATENCY_ARVLD_ARRDY,
    AXI_TMU_LATENCY_ARVLD_RVLD,
    AXI_TMU_LATENCY_RVLD_RRDY,
    AXI_TMU_LATENCY_RVLD_RLAST
  } axi_tmu_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] AXI_TMU_PERMIT [21] = '{
    4'b 0001, // index[ 0] AXI_TMU_BUDGET_AWVLD_AWRDY
    4'b 0001, // index[ 1] AXI_TMU_BUDGET_AWHS_WFIRST
    4'b 0001, // index[ 2] AXI_TMU_BUDGET_WVLD_WRDY
    4'b 0001, // index[ 3] AXI_TMU_BUDGET_W_LIVENESS
    4'b 0001, // index[ 4] AXI_TMU_BUDGET_WLAST_BVLD
    4'b 0001, // index[ 5] AXI_TMU_BUDGET_BVLD_BRDY
    4'b 0001, // index[ 6] AXI_TMU_BUDGET_ARVLD_ARRDY
    4'b 0001, // index[ 7] AXI_TMU_BUDGET_RVLD_RRDY
    4'b 0001, // index[ 8] AXI_TMU_BUDGET_ARHS_RFIRST
    4'b 0001, // index[ 9] AXI_TMU_BUDGET_R_LIVENESS
    4'b 0001, // index[10] AXI_TMU_RESET
    4'b 1111, // index[11] AXI_TMU_FAULT_LOG
    4'b 0011, // index[12] AXI_TMU_LATENCY_AWVLD_WFIRST
    4'b 0011, // index[13] AXI_TMU_LATENCY_WVLD_WRDY
    4'b 0011, // index[14] AXI_TMU_LATENCY_WVLD_WLAST
    4'b 0011, // index[15] AXI_TMU_LATENCY_WLAST_BVLD
    4'b 0011, // index[16] AXI_TMU_LATENCY_BVLD_BRDY
    4'b 0011, // index[17] AXI_TMU_LATENCY_ARVLD_ARRDY
    4'b 0011, // index[18] AXI_TMU_LATENCY_ARVLD_RVLD
    4'b 0011, // index[19] AXI_TMU_LATENCY_RVLD_RRDY
    4'b 0011  // index[20] AXI_TMU_LATENCY_RVLD_RLAST
  };

endpackage

