// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module axi_tmu_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 7
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output axi_tmu_reg_pkg::axi_tmu_reg2hw_t reg2hw, // Write
  input  axi_tmu_reg_pkg::axi_tmu_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import axi_tmu_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [7:0] budget_awvld_awrdy_wd;
  logic budget_awvld_awrdy_we;
  logic [7:0] budget_awhs_wfirst_wd;
  logic budget_awhs_wfirst_we;
  logic [7:0] budget_wvld_wrdy_wd;
  logic budget_wvld_wrdy_we;
  logic [7:0] budget_w_liveness_wd;
  logic budget_w_liveness_we;
  logic [7:0] budget_wlast_bvld_wd;
  logic budget_wlast_bvld_we;
  logic [7:0] budget_bvld_brdy_wd;
  logic budget_bvld_brdy_we;
  logic [7:0] budget_arvld_arrdy_wd;
  logic budget_arvld_arrdy_we;
  logic [7:0] budget_rvld_rrdy_wd;
  logic budget_rvld_rrdy_we;
  logic [7:0] budget_arhs_rfirst_wd;
  logic budget_arhs_rfirst_we;
  logic [7:0] budget_r_liveness_wd;
  logic budget_r_liveness_we;
  logic reset_qs;
  logic fault_log_fault_valid_qs;
  logic fault_log_fault_valid_wd;
  logic fault_log_fault_valid_we;
  logic [2:0] fault_log_fault_type_qs;
  logic [2:0] fault_log_fault_type_wd;
  logic fault_log_fault_type_we;
  logic fault_log_fault_dir_qs;
  logic fault_log_fault_dir_wd;
  logic fault_log_fault_dir_we;
  logic [3:0] fault_log_fault_phase_qs;
  logic [3:0] fault_log_fault_phase_wd;
  logic fault_log_fault_phase_we;
  logic [15:0] fault_log_fault_id_qs;
  logic [15:0] fault_log_fault_id_wd;
  logic fault_log_fault_id_we;
  logic [9:0] latency_awvld_wfirst_qs;
  logic [9:0] latency_wvld_wrdy_qs;
  logic [9:0] latency_wvld_wlast_qs;
  logic [9:0] latency_wlast_bvld_qs;
  logic [9:0] latency_bvld_brdy_qs;
  logic [9:0] latency_arvld_arrdy_qs;
  logic [9:0] latency_arvld_rvld_qs;
  logic [9:0] latency_rvld_rrdy_qs;
  logic [9:0] latency_rvld_rlast_qs;

  // Register instances
  // R[budget_awvld_awrdy]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_awvld_awrdy (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_awvld_awrdy_we),
    .wd     (budget_awvld_awrdy_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_awvld_awrdy.q ),

    .qs     ()
  );


  // R[budget_awhs_wfirst]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_awhs_wfirst (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_awhs_wfirst_we),
    .wd     (budget_awhs_wfirst_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_awhs_wfirst.q ),

    .qs     ()
  );


  // R[budget_wvld_wrdy]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_wvld_wrdy (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_wvld_wrdy_we),
    .wd     (budget_wvld_wrdy_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_wvld_wrdy.q ),

    .qs     ()
  );


  // R[budget_w_liveness]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_w_liveness (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_w_liveness_we),
    .wd     (budget_w_liveness_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_w_liveness.q ),

    .qs     ()
  );


  // R[budget_wlast_bvld]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_wlast_bvld (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_wlast_bvld_we),
    .wd     (budget_wlast_bvld_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_wlast_bvld.q ),

    .qs     ()
  );


  // R[budget_bvld_brdy]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_bvld_brdy (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_bvld_brdy_we),
    .wd     (budget_bvld_brdy_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_bvld_brdy.q ),

    .qs     ()
  );


  // R[budget_arvld_arrdy]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_arvld_arrdy (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_arvld_arrdy_we),
    .wd     (budget_arvld_arrdy_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_arvld_arrdy.q ),

    .qs     ()
  );


  // R[budget_rvld_rrdy]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_rvld_rrdy (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_rvld_rrdy_we),
    .wd     (budget_rvld_rrdy_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_rvld_rrdy.q ),

    .qs     ()
  );


  // R[budget_arhs_rfirst]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_arhs_rfirst (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_arhs_rfirst_we),
    .wd     (budget_arhs_rfirst_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_arhs_rfirst.q ),

    .qs     ()
  );


  // R[budget_r_liveness]: V(False)

  prim_subreg #(
    .DW      (8),
    .SWACCESS("WO"),
    .RESVAL  (8'h0)
  ) u_budget_r_liveness (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (budget_r_liveness_we),
    .wd     (budget_r_liveness_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.budget_r_liveness.q ),

    .qs     ()
  );


  // R[reset]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_reset (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.reset.de),
    .d      (hw2reg.reset.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.reset.q ),

    // to register interface (read)
    .qs     (reset_qs)
  );


  // R[fault_log]: V(False)

  //   F[fault_valid]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_fault_log_fault_valid (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fault_log_fault_valid_we),
    .wd     (fault_log_fault_valid_wd),

    // from internal hardware
    .de     (hw2reg.fault_log.fault_valid.de),
    .d      (hw2reg.fault_log.fault_valid.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fault_log.fault_valid.q ),

    // to register interface (read)
    .qs     (fault_log_fault_valid_qs)
  );


  //   F[fault_type]: 3:1
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RW"),
    .RESVAL  (3'h0)
  ) u_fault_log_fault_type (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fault_log_fault_type_we),
    .wd     (fault_log_fault_type_wd),

    // from internal hardware
    .de     (hw2reg.fault_log.fault_type.de),
    .d      (hw2reg.fault_log.fault_type.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fault_log.fault_type.q ),

    // to register interface (read)
    .qs     (fault_log_fault_type_qs)
  );


  //   F[fault_dir]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_fault_log_fault_dir (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fault_log_fault_dir_we),
    .wd     (fault_log_fault_dir_wd),

    // from internal hardware
    .de     (hw2reg.fault_log.fault_dir.de),
    .d      (hw2reg.fault_log.fault_dir.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fault_log.fault_dir.q ),

    // to register interface (read)
    .qs     (fault_log_fault_dir_qs)
  );


  //   F[fault_phase]: 8:5
  prim_subreg #(
    .DW      (4),
    .SWACCESS("RW"),
    .RESVAL  (4'h0)
  ) u_fault_log_fault_phase (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fault_log_fault_phase_we),
    .wd     (fault_log_fault_phase_wd),

    // from internal hardware
    .de     (hw2reg.fault_log.fault_phase.de),
    .d      (hw2reg.fault_log.fault_phase.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fault_log.fault_phase.q ),

    // to register interface (read)
    .qs     (fault_log_fault_phase_qs)
  );


  //   F[fault_id]: 24:9
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_fault_log_fault_id (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fault_log_fault_id_we),
    .wd     (fault_log_fault_id_wd),

    // from internal hardware
    .de     (hw2reg.fault_log.fault_id.de),
    .d      (hw2reg.fault_log.fault_id.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fault_log.fault_id.q ),

    // to register interface (read)
    .qs     (fault_log_fault_id_qs)
  );


  // R[latency_awvld_wfirst]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RO"),
    .RESVAL  (10'h0)
  ) u_latency_awvld_wfirst (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.latency_awvld_wfirst.de),
    .d      (hw2reg.latency_awvld_wfirst.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.latency_awvld_wfirst.q ),

    // to register interface (read)
    .qs     (latency_awvld_wfirst_qs)
  );


  // R[latency_wvld_wrdy]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RO"),
    .RESVAL  (10'h0)
  ) u_latency_wvld_wrdy (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.latency_wvld_wrdy.de),
    .d      (hw2reg.latency_wvld_wrdy.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.latency_wvld_wrdy.q ),

    // to register interface (read)
    .qs     (latency_wvld_wrdy_qs)
  );


  // R[latency_wvld_wlast]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RO"),
    .RESVAL  (10'h0)
  ) u_latency_wvld_wlast (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.latency_wvld_wlast.de),
    .d      (hw2reg.latency_wvld_wlast.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.latency_wvld_wlast.q ),

    // to register interface (read)
    .qs     (latency_wvld_wlast_qs)
  );


  // R[latency_wlast_bvld]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RO"),
    .RESVAL  (10'h0)
  ) u_latency_wlast_bvld (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.latency_wlast_bvld.de),
    .d      (hw2reg.latency_wlast_bvld.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.latency_wlast_bvld.q ),

    // to register interface (read)
    .qs     (latency_wlast_bvld_qs)
  );


  // R[latency_bvld_brdy]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RO"),
    .RESVAL  (10'h0)
  ) u_latency_bvld_brdy (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.latency_bvld_brdy.de),
    .d      (hw2reg.latency_bvld_brdy.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.latency_bvld_brdy.q ),

    // to register interface (read)
    .qs     (latency_bvld_brdy_qs)
  );


  // R[latency_arvld_arrdy]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RO"),
    .RESVAL  (10'h0)
  ) u_latency_arvld_arrdy (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.latency_arvld_arrdy.de),
    .d      (hw2reg.latency_arvld_arrdy.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.latency_arvld_arrdy.q ),

    // to register interface (read)
    .qs     (latency_arvld_arrdy_qs)
  );


  // R[latency_arvld_rvld]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RO"),
    .RESVAL  (10'h0)
  ) u_latency_arvld_rvld (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.latency_arvld_rvld.de),
    .d      (hw2reg.latency_arvld_rvld.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.latency_arvld_rvld.q ),

    // to register interface (read)
    .qs     (latency_arvld_rvld_qs)
  );


  // R[latency_rvld_rrdy]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RO"),
    .RESVAL  (10'h0)
  ) u_latency_rvld_rrdy (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.latency_rvld_rrdy.de),
    .d      (hw2reg.latency_rvld_rrdy.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.latency_rvld_rrdy.q ),

    // to register interface (read)
    .qs     (latency_rvld_rrdy_qs)
  );


  // R[latency_rvld_rlast]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RO"),
    .RESVAL  (10'h0)
  ) u_latency_rvld_rlast (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.latency_rvld_rlast.de),
    .d      (hw2reg.latency_rvld_rlast.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.latency_rvld_rlast.q ),

    // to register interface (read)
    .qs     (latency_rvld_rlast_qs)
  );




  logic [20:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == AXI_TMU_BUDGET_AWVLD_AWRDY_OFFSET);
    addr_hit[ 1] = (reg_addr == AXI_TMU_BUDGET_AWHS_WFIRST_OFFSET);
    addr_hit[ 2] = (reg_addr == AXI_TMU_BUDGET_WVLD_WRDY_OFFSET);
    addr_hit[ 3] = (reg_addr == AXI_TMU_BUDGET_W_LIVENESS_OFFSET);
    addr_hit[ 4] = (reg_addr == AXI_TMU_BUDGET_WLAST_BVLD_OFFSET);
    addr_hit[ 5] = (reg_addr == AXI_TMU_BUDGET_BVLD_BRDY_OFFSET);
    addr_hit[ 6] = (reg_addr == AXI_TMU_BUDGET_ARVLD_ARRDY_OFFSET);
    addr_hit[ 7] = (reg_addr == AXI_TMU_BUDGET_RVLD_RRDY_OFFSET);
    addr_hit[ 8] = (reg_addr == AXI_TMU_BUDGET_ARHS_RFIRST_OFFSET);
    addr_hit[ 9] = (reg_addr == AXI_TMU_BUDGET_R_LIVENESS_OFFSET);
    addr_hit[10] = (reg_addr == AXI_TMU_RESET_OFFSET);
    addr_hit[11] = (reg_addr == AXI_TMU_FAULT_LOG_OFFSET);
    addr_hit[12] = (reg_addr == AXI_TMU_LATENCY_AWVLD_WFIRST_OFFSET);
    addr_hit[13] = (reg_addr == AXI_TMU_LATENCY_WVLD_WRDY_OFFSET);
    addr_hit[14] = (reg_addr == AXI_TMU_LATENCY_WVLD_WLAST_OFFSET);
    addr_hit[15] = (reg_addr == AXI_TMU_LATENCY_WLAST_BVLD_OFFSET);
    addr_hit[16] = (reg_addr == AXI_TMU_LATENCY_BVLD_BRDY_OFFSET);
    addr_hit[17] = (reg_addr == AXI_TMU_LATENCY_ARVLD_ARRDY_OFFSET);
    addr_hit[18] = (reg_addr == AXI_TMU_LATENCY_ARVLD_RVLD_OFFSET);
    addr_hit[19] = (reg_addr == AXI_TMU_LATENCY_RVLD_RRDY_OFFSET);
    addr_hit[20] = (reg_addr == AXI_TMU_LATENCY_RVLD_RLAST_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(AXI_TMU_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(AXI_TMU_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(AXI_TMU_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(AXI_TMU_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(AXI_TMU_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(AXI_TMU_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(AXI_TMU_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(AXI_TMU_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(AXI_TMU_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(AXI_TMU_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(AXI_TMU_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(AXI_TMU_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(AXI_TMU_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(AXI_TMU_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(AXI_TMU_PERMIT[14] & ~reg_be))) |
               (addr_hit[15] & (|(AXI_TMU_PERMIT[15] & ~reg_be))) |
               (addr_hit[16] & (|(AXI_TMU_PERMIT[16] & ~reg_be))) |
               (addr_hit[17] & (|(AXI_TMU_PERMIT[17] & ~reg_be))) |
               (addr_hit[18] & (|(AXI_TMU_PERMIT[18] & ~reg_be))) |
               (addr_hit[19] & (|(AXI_TMU_PERMIT[19] & ~reg_be))) |
               (addr_hit[20] & (|(AXI_TMU_PERMIT[20] & ~reg_be)))));
  end

  assign budget_awvld_awrdy_we = addr_hit[0] & reg_we & !reg_error;
  assign budget_awvld_awrdy_wd = reg_wdata[7:0];

  assign budget_awhs_wfirst_we = addr_hit[1] & reg_we & !reg_error;
  assign budget_awhs_wfirst_wd = reg_wdata[7:0];

  assign budget_wvld_wrdy_we = addr_hit[2] & reg_we & !reg_error;
  assign budget_wvld_wrdy_wd = reg_wdata[7:0];

  assign budget_w_liveness_we = addr_hit[3] & reg_we & !reg_error;
  assign budget_w_liveness_wd = reg_wdata[7:0];

  assign budget_wlast_bvld_we = addr_hit[4] & reg_we & !reg_error;
  assign budget_wlast_bvld_wd = reg_wdata[7:0];

  assign budget_bvld_brdy_we = addr_hit[5] & reg_we & !reg_error;
  assign budget_bvld_brdy_wd = reg_wdata[7:0];

  assign budget_arvld_arrdy_we = addr_hit[6] & reg_we & !reg_error;
  assign budget_arvld_arrdy_wd = reg_wdata[7:0];

  assign budget_rvld_rrdy_we = addr_hit[7] & reg_we & !reg_error;
  assign budget_rvld_rrdy_wd = reg_wdata[7:0];

  assign budget_arhs_rfirst_we = addr_hit[8] & reg_we & !reg_error;
  assign budget_arhs_rfirst_wd = reg_wdata[7:0];

  assign budget_r_liveness_we = addr_hit[9] & reg_we & !reg_error;
  assign budget_r_liveness_wd = reg_wdata[7:0];

  assign fault_log_fault_valid_we = addr_hit[11] & reg_we & !reg_error;
  assign fault_log_fault_valid_wd = reg_wdata[0];

  assign fault_log_fault_type_we = addr_hit[11] & reg_we & !reg_error;
  assign fault_log_fault_type_wd = reg_wdata[3:1];

  assign fault_log_fault_dir_we = addr_hit[11] & reg_we & !reg_error;
  assign fault_log_fault_dir_wd = reg_wdata[4];

  assign fault_log_fault_phase_we = addr_hit[11] & reg_we & !reg_error;
  assign fault_log_fault_phase_wd = reg_wdata[8:5];

  assign fault_log_fault_id_we = addr_hit[11] & reg_we & !reg_error;
  assign fault_log_fault_id_wd = reg_wdata[24:9];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[1]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[2]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[3]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[4]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[5]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[6]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[7]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[8]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[9]: begin
        reg_rdata_next[7:0] = '0;
      end

      addr_hit[10]: begin
        reg_rdata_next[0] = reset_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[0] = fault_log_fault_valid_qs;
        reg_rdata_next[3:1] = fault_log_fault_type_qs;
        reg_rdata_next[4] = fault_log_fault_dir_qs;
        reg_rdata_next[8:5] = fault_log_fault_phase_qs;
        reg_rdata_next[24:9] = fault_log_fault_id_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[9:0] = latency_awvld_wfirst_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[9:0] = latency_wvld_wrdy_qs;
      end

      addr_hit[14]: begin
        reg_rdata_next[9:0] = latency_wvld_wlast_qs;
      end

      addr_hit[15]: begin
        reg_rdata_next[9:0] = latency_wlast_bvld_qs;
      end

      addr_hit[16]: begin
        reg_rdata_next[9:0] = latency_bvld_brdy_qs;
      end

      addr_hit[17]: begin
        reg_rdata_next[9:0] = latency_arvld_arrdy_qs;
      end

      addr_hit[18]: begin
        reg_rdata_next[9:0] = latency_arvld_rvld_qs;
      end

      addr_hit[19]: begin
        reg_rdata_next[9:0] = latency_rvld_rrdy_qs;
      end

      addr_hit[20]: begin
        reg_rdata_next[9:0] = latency_rvld_rlast_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module axi_tmu_reg_top_intf
#(
  parameter int AW = 7,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output axi_tmu_reg_pkg::axi_tmu_reg2hw_t reg2hw, // Write
  input  axi_tmu_reg_pkg::axi_tmu_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  axi_tmu_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


