// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package axi_rt_regs_pkg;

    localparam AXI_RT_REGS_DATA_WIDTH = 32;
    localparam AXI_RT_REGS_MIN_ADDR_WIDTH = 11;
    localparam AXI_RT_REGS_SIZE = 'h418;
    localparam NumMrg = 'h8;
    localparam NumReg = 'h10;
    localparam MajorVer = 'h0;
    localparam MinorVer = 'h0;
    localparam PatchVer = 'h0;

    typedef struct {
        logic next;
    } axi_rt_regs__rt_bypassed__bypassed__in_t;

    typedef struct {
        axi_rt_regs__rt_bypassed__bypassed__in_t bypassed;
    } axi_rt_regs__rt_bypassed__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__write_budget_left__budget__in_t;

    typedef struct {
        axi_rt_regs__write_budget_left__budget__in_t budget;
    } axi_rt_regs__write_budget_left__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__read_budget_left__budget__in_t;

    typedef struct {
        axi_rt_regs__read_budget_left__budget__in_t budget;
    } axi_rt_regs__read_budget_left__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__write_period_left__period__in_t;

    typedef struct {
        axi_rt_regs__write_period_left__period__in_t period;
    } axi_rt_regs__write_period_left__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__read_period_left__period__in_t;

    typedef struct {
        axi_rt_regs__read_period_left__period__in_t period;
    } axi_rt_regs__read_period_left__in_t;

    typedef struct {
        logic next;
    } axi_rt_regs__isolate__isolate__in_t;

    typedef struct {
        axi_rt_regs__isolate__isolate__in_t isolate;
    } axi_rt_regs__isolate__in_t;

    typedef struct {
        logic next;
    } axi_rt_regs__isolated__isolated__in_t;

    typedef struct {
        axi_rt_regs__isolated__isolated__in_t isolated;
    } axi_rt_regs__isolated__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__num_managers__num_managers__in_t;

    typedef struct {
        axi_rt_regs__num_managers__num_managers__in_t num_managers;
    } axi_rt_regs__num_managers__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__addr_width__addr_width__in_t;

    typedef struct {
        axi_rt_regs__addr_width__addr_width__in_t addr_width;
    } axi_rt_regs__addr_width__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__data_width__data_width__in_t;

    typedef struct {
        axi_rt_regs__data_width__data_width__in_t data_width;
    } axi_rt_regs__data_width__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__id_width__id_width__in_t;

    typedef struct {
        axi_rt_regs__id_width__id_width__in_t id_width;
    } axi_rt_regs__id_width__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__user_width__user_width__in_t;

    typedef struct {
        axi_rt_regs__user_width__user_width__in_t user_width;
    } axi_rt_regs__user_width__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__num_pending__num_pending__in_t;

    typedef struct {
        axi_rt_regs__num_pending__num_pending__in_t num_pending;
    } axi_rt_regs__num_pending__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__w_buffer_depth__w_buffer_depth__in_t;

    typedef struct {
        axi_rt_regs__w_buffer_depth__w_buffer_depth__in_t w_buffer_depth;
    } axi_rt_regs__w_buffer_depth__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__num_addr_regions__num_addr_regions__in_t;

    typedef struct {
        axi_rt_regs__num_addr_regions__num_addr_regions__in_t num_addr_regions;
    } axi_rt_regs__num_addr_regions__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__period_width__period_width__in_t;

    typedef struct {
        axi_rt_regs__period_width__period_width__in_t period_width;
    } axi_rt_regs__period_width__in_t;

    typedef struct {
        logic [31:0] next;
    } axi_rt_regs__budget_width__budget_width__in_t;

    typedef struct {
        axi_rt_regs__budget_width__budget_width__in_t budget_width;
    } axi_rt_regs__budget_width__in_t;

    typedef struct {
        axi_rt_regs__rt_bypassed__in_t rt_bypassed[8];
        axi_rt_regs__write_budget_left__in_t write_budget_left[16];
        axi_rt_regs__read_budget_left__in_t read_budget_left[16];
        axi_rt_regs__write_period_left__in_t write_period_left[16];
        axi_rt_regs__read_period_left__in_t read_period_left[16];
        axi_rt_regs__isolate__in_t isolate[8];
        axi_rt_regs__isolated__in_t isolated[8];
        axi_rt_regs__num_managers__in_t num_managers;
        axi_rt_regs__addr_width__in_t addr_width;
        axi_rt_regs__data_width__in_t data_width;
        axi_rt_regs__id_width__in_t id_width;
        axi_rt_regs__user_width__in_t user_width;
        axi_rt_regs__num_pending__in_t num_pending;
        axi_rt_regs__w_buffer_depth__in_t w_buffer_depth;
        axi_rt_regs__num_addr_regions__in_t num_addr_regions;
        axi_rt_regs__period_width__in_t period_width;
        axi_rt_regs__budget_width__in_t budget_width;
    } axi_rt_regs__in_t;

    typedef struct {
        logic value;
    } axi_rt_regs__rt_enable__enable__out_t;

    typedef struct {
        axi_rt_regs__rt_enable__enable__out_t enable;
    } axi_rt_regs__rt_enable__out_t;

    typedef struct {
        logic [7:0] value;
    } axi_rt_regs__len_limit__len__out_t;

    typedef struct {
        axi_rt_regs__len_limit__len__out_t len;
    } axi_rt_regs__len_limit__out_t;

    typedef struct {
        logic value;
    } axi_rt_regs__imtu_enable__enable__out_t;

    typedef struct {
        axi_rt_regs__imtu_enable__enable__out_t enable;
    } axi_rt_regs__imtu_enable__out_t;

    typedef struct {
        logic value;
    } axi_rt_regs__imtu_abort__abort__out_t;

    typedef struct {
        axi_rt_regs__imtu_abort__abort__out_t abort;
    } axi_rt_regs__imtu_abort__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_rt_regs__start_addr_sub_low__addr__out_t;

    typedef struct {
        axi_rt_regs__start_addr_sub_low__addr__out_t addr;
    } axi_rt_regs__start_addr_sub_low__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_rt_regs__start_addr_sub_high__addr__out_t;

    typedef struct {
        axi_rt_regs__start_addr_sub_high__addr__out_t addr;
    } axi_rt_regs__start_addr_sub_high__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_rt_regs__end_addr_sub_low__addr__out_t;

    typedef struct {
        axi_rt_regs__end_addr_sub_low__addr__out_t addr;
    } axi_rt_regs__end_addr_sub_low__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_rt_regs__end_addr_sub_high__addr__out_t;

    typedef struct {
        axi_rt_regs__end_addr_sub_high__addr__out_t addr;
    } axi_rt_regs__end_addr_sub_high__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_rt_regs__write_budget__budget__out_t;

    typedef struct {
        axi_rt_regs__write_budget__budget__out_t budget;
    } axi_rt_regs__write_budget__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_rt_regs__read_budget__budget__out_t;

    typedef struct {
        axi_rt_regs__read_budget__budget__out_t budget;
    } axi_rt_regs__read_budget__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_rt_regs__write_period__period__out_t;

    typedef struct {
        axi_rt_regs__write_period__period__out_t period;
    } axi_rt_regs__write_period__out_t;

    typedef struct {
        logic [31:0] value;
    } axi_rt_regs__read_period__period__out_t;

    typedef struct {
        axi_rt_regs__read_period__period__out_t period;
    } axi_rt_regs__read_period__out_t;

    typedef struct {
        axi_rt_regs__rt_enable__out_t rt_enable[8];
        axi_rt_regs__len_limit__out_t len_limit[8];
        axi_rt_regs__imtu_enable__out_t imtu_enable[8];
        axi_rt_regs__imtu_abort__out_t imtu_abort[8];
        axi_rt_regs__start_addr_sub_low__out_t start_addr_sub_low[16];
        axi_rt_regs__start_addr_sub_high__out_t start_addr_sub_high[16];
        axi_rt_regs__end_addr_sub_low__out_t end_addr_sub_low[16];
        axi_rt_regs__end_addr_sub_high__out_t end_addr_sub_high[16];
        axi_rt_regs__write_budget__out_t write_budget[16];
        axi_rt_regs__read_budget__out_t read_budget[16];
        axi_rt_regs__write_period__out_t write_period[16];
        axi_rt_regs__read_period__out_t read_period[16];
    } axi_rt_regs__out_t;
endpackage
