// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module axi_rt_regs (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [10:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input axi_rt_regs_pkg::axi_rt_regs__in_t hwif_in,
        output axi_rt_regs_pkg::axi_rt_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [10:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[10:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic major_version;
        logic minor_version;
        logic patch_version;
        logic rt_enable[8];
        logic rt_bypassed[8];
        logic len_limit[8];
        logic imtu_enable[8];
        logic imtu_abort[8];
        logic start_addr_sub_low[16];
        logic start_addr_sub_high[16];
        logic end_addr_sub_low[16];
        logic end_addr_sub_high[16];
        logic write_budget[16];
        logic read_budget[16];
        logic write_period[16];
        logic read_period[16];
        logic write_budget_left[16];
        logic read_budget_left[16];
        logic write_period_left[16];
        logic read_period_left[16];
        logic isolate[8];
        logic isolated[8];
        logic num_managers;
        logic addr_width;
        logic data_width;
        logic id_width;
        logic user_width;
        logic num_pending;
        logic w_buffer_depth;
        logic num_addr_regions;
        logic period_width;
        logic budget_width;
        logic max_num_managers;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [10:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.major_version = cpuif_req_masked & (cpuif_addr == 11'h0) & !cpuif_req_is_wr;
        decoded_reg_strb.minor_version = cpuif_req_masked & (cpuif_addr == 11'h4) & !cpuif_req_is_wr;
        decoded_reg_strb.patch_version = cpuif_req_masked & (cpuif_addr == 11'h8) & !cpuif_req_is_wr;
        for(int i0=0; i0<8; i0++) begin
            decoded_reg_strb.rt_enable[i0] = cpuif_req_masked & (cpuif_addr == 11'hc + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<8; i0++) begin
            decoded_reg_strb.rt_bypassed[i0] = cpuif_req_masked & (cpuif_addr == 11'h2c + (11)'(i0) * 11'h4) & !cpuif_req_is_wr;
        end
        for(int i0=0; i0<8; i0++) begin
            decoded_reg_strb.len_limit[i0] = cpuif_req_masked & (cpuif_addr == 11'h4c + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<8; i0++) begin
            decoded_reg_strb.imtu_enable[i0] = cpuif_req_masked & (cpuif_addr == 11'h6c + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<8; i0++) begin
            decoded_reg_strb.imtu_abort[i0] = cpuif_req_masked & (cpuif_addr == 11'h8c + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.start_addr_sub_low[i0] = cpuif_req_masked & (cpuif_addr == 11'hac + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.start_addr_sub_high[i0] = cpuif_req_masked & (cpuif_addr == 11'hec + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.end_addr_sub_low[i0] = cpuif_req_masked & (cpuif_addr == 11'h12c + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.end_addr_sub_high[i0] = cpuif_req_masked & (cpuif_addr == 11'h16c + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.write_budget[i0] = cpuif_req_masked & (cpuif_addr == 11'h1ac + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.read_budget[i0] = cpuif_req_masked & (cpuif_addr == 11'h1ec + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.write_period[i0] = cpuif_req_masked & (cpuif_addr == 11'h22c + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.read_period[i0] = cpuif_req_masked & (cpuif_addr == 11'h26c + (11)'(i0) * 11'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.write_budget_left[i0] = cpuif_req_masked & (cpuif_addr == 11'h2ac + (11)'(i0) * 11'h4) & !cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.read_budget_left[i0] = cpuif_req_masked & (cpuif_addr == 11'h2ec + (11)'(i0) * 11'h4) & !cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.write_period_left[i0] = cpuif_req_masked & (cpuif_addr == 11'h32c + (11)'(i0) * 11'h4) & !cpuif_req_is_wr;
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.read_period_left[i0] = cpuif_req_masked & (cpuif_addr == 11'h36c + (11)'(i0) * 11'h4) & !cpuif_req_is_wr;
        end
        for(int i0=0; i0<8; i0++) begin
            decoded_reg_strb.isolate[i0] = cpuif_req_masked & (cpuif_addr == 11'h3ac + (11)'(i0) * 11'h4) & !cpuif_req_is_wr;
        end
        for(int i0=0; i0<8; i0++) begin
            decoded_reg_strb.isolated[i0] = cpuif_req_masked & (cpuif_addr == 11'h3cc + (11)'(i0) * 11'h4) & !cpuif_req_is_wr;
        end
        decoded_reg_strb.num_managers = cpuif_req_masked & (cpuif_addr == 11'h3ec) & !cpuif_req_is_wr;
        decoded_reg_strb.addr_width = cpuif_req_masked & (cpuif_addr == 11'h3f0) & !cpuif_req_is_wr;
        decoded_reg_strb.data_width = cpuif_req_masked & (cpuif_addr == 11'h3f4) & !cpuif_req_is_wr;
        decoded_reg_strb.id_width = cpuif_req_masked & (cpuif_addr == 11'h3f8) & !cpuif_req_is_wr;
        decoded_reg_strb.user_width = cpuif_req_masked & (cpuif_addr == 11'h3fc) & !cpuif_req_is_wr;
        decoded_reg_strb.num_pending = cpuif_req_masked & (cpuif_addr == 11'h400) & !cpuif_req_is_wr;
        decoded_reg_strb.w_buffer_depth = cpuif_req_masked & (cpuif_addr == 11'h404) & !cpuif_req_is_wr;
        decoded_reg_strb.num_addr_regions = cpuif_req_masked & (cpuif_addr == 11'h408) & !cpuif_req_is_wr;
        decoded_reg_strb.period_width = cpuif_req_masked & (cpuif_addr == 11'h40c) & !cpuif_req_is_wr;
        decoded_reg_strb.budget_width = cpuif_req_masked & (cpuif_addr == 11'h410) & !cpuif_req_is_wr;
        decoded_reg_strb.max_num_managers = cpuif_req_masked & (cpuif_addr == 11'h414) & !cpuif_req_is_wr;
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } enable;
        } rt_enable[8];
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } len;
        } len_limit[8];
        struct {
            struct {
                logic next;
                logic load_next;
            } enable;
        } imtu_enable[8];
        struct {
            struct {
                logic next;
                logic load_next;
            } abort;
        } imtu_abort[8];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } addr;
        } start_addr_sub_low[16];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } addr;
        } start_addr_sub_high[16];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } addr;
        } end_addr_sub_low[16];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } addr;
        } end_addr_sub_high[16];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } budget;
        } write_budget[16];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } budget;
        } read_budget[16];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } period;
        } write_period[16];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } period;
        } read_period[16];
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } enable;
        } rt_enable[8];
        struct {
            struct {
                logic [7:0] value;
            } len;
        } len_limit[8];
        struct {
            struct {
                logic value;
            } enable;
        } imtu_enable[8];
        struct {
            struct {
                logic value;
            } abort;
        } imtu_abort[8];
        struct {
            struct {
                logic [31:0] value;
            } addr;
        } start_addr_sub_low[16];
        struct {
            struct {
                logic [31:0] value;
            } addr;
        } start_addr_sub_high[16];
        struct {
            struct {
                logic [31:0] value;
            } addr;
        } end_addr_sub_low[16];
        struct {
            struct {
                logic [31:0] value;
            } addr;
        } end_addr_sub_high[16];
        struct {
            struct {
                logic [31:0] value;
            } budget;
        } write_budget[16];
        struct {
            struct {
                logic [31:0] value;
            } budget;
        } read_budget[16];
        struct {
            struct {
                logic [31:0] value;
            } period;
        } write_period[16];
        struct {
            struct {
                logic [31:0] value;
            } period;
        } read_period[16];
    } field_storage_t;
    field_storage_t field_storage;

    for(genvar i0=0; i0<8; i0++) begin
        // Field: axi_rt_regs.rt_enable[].enable
        always_comb begin
            automatic logic [0:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.rt_enable[i0].enable.value;
            load_next_c = '0;
            if(decoded_reg_strb.rt_enable[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.rt_enable[i0].enable.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
                load_next_c = '1;
            end
            field_combo.rt_enable[i0].enable.next = next_c;
            field_combo.rt_enable[i0].enable.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.rt_enable[i0].enable.value <= 1'h0;
            end else begin
                if(field_combo.rt_enable[i0].enable.load_next) begin
                    field_storage.rt_enable[i0].enable.value <= field_combo.rt_enable[i0].enable.next;
                end
            end
        end
        assign hwif_out.rt_enable[i0].enable.value = field_storage.rt_enable[i0].enable.value;
    end
    for(genvar i0=0; i0<8; i0++) begin
        // Field: axi_rt_regs.len_limit[].len
        always_comb begin
            automatic logic [7:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.len_limit[i0].len.value;
            load_next_c = '0;
            if(decoded_reg_strb.len_limit[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.len_limit[i0].len.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
                load_next_c = '1;
            end
            field_combo.len_limit[i0].len.next = next_c;
            field_combo.len_limit[i0].len.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.len_limit[i0].len.value <= 8'h0;
            end else begin
                if(field_combo.len_limit[i0].len.load_next) begin
                    field_storage.len_limit[i0].len.value <= field_combo.len_limit[i0].len.next;
                end
            end
        end
        assign hwif_out.len_limit[i0].len.value = field_storage.len_limit[i0].len.value;
    end
    for(genvar i0=0; i0<8; i0++) begin
        // Field: axi_rt_regs.imtu_enable[].enable
        always_comb begin
            automatic logic [0:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.imtu_enable[i0].enable.value;
            load_next_c = '0;
            if(decoded_reg_strb.imtu_enable[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.imtu_enable[i0].enable.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
                load_next_c = '1;
            end
            field_combo.imtu_enable[i0].enable.next = next_c;
            field_combo.imtu_enable[i0].enable.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.imtu_enable[i0].enable.value <= 1'h0;
            end else begin
                if(field_combo.imtu_enable[i0].enable.load_next) begin
                    field_storage.imtu_enable[i0].enable.value <= field_combo.imtu_enable[i0].enable.next;
                end
            end
        end
        assign hwif_out.imtu_enable[i0].enable.value = field_storage.imtu_enable[i0].enable.value;
    end
    for(genvar i0=0; i0<8; i0++) begin
        // Field: axi_rt_regs.imtu_abort[].abort
        always_comb begin
            automatic logic [0:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.imtu_abort[i0].abort.value;
            load_next_c = '0;
            if(decoded_reg_strb.imtu_abort[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.imtu_abort[i0].abort.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
                load_next_c = '1;
            end
            field_combo.imtu_abort[i0].abort.next = next_c;
            field_combo.imtu_abort[i0].abort.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.imtu_abort[i0].abort.value <= 1'h0;
            end else begin
                if(field_combo.imtu_abort[i0].abort.load_next) begin
                    field_storage.imtu_abort[i0].abort.value <= field_combo.imtu_abort[i0].abort.next;
                end
            end
        end
        assign hwif_out.imtu_abort[i0].abort.value = field_storage.imtu_abort[i0].abort.value;
    end
    for(genvar i0=0; i0<16; i0++) begin
        // Field: axi_rt_regs.start_addr_sub_low[].addr
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.start_addr_sub_low[i0].addr.value;
            load_next_c = '0;
            if(decoded_reg_strb.start_addr_sub_low[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.start_addr_sub_low[i0].addr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.start_addr_sub_low[i0].addr.next = next_c;
            field_combo.start_addr_sub_low[i0].addr.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.start_addr_sub_low[i0].addr.value <= 32'h0;
            end else begin
                if(field_combo.start_addr_sub_low[i0].addr.load_next) begin
                    field_storage.start_addr_sub_low[i0].addr.value <= field_combo.start_addr_sub_low[i0].addr.next;
                end
            end
        end
        assign hwif_out.start_addr_sub_low[i0].addr.value = field_storage.start_addr_sub_low[i0].addr.value;
    end
    for(genvar i0=0; i0<16; i0++) begin
        // Field: axi_rt_regs.start_addr_sub_high[].addr
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.start_addr_sub_high[i0].addr.value;
            load_next_c = '0;
            if(decoded_reg_strb.start_addr_sub_high[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.start_addr_sub_high[i0].addr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.start_addr_sub_high[i0].addr.next = next_c;
            field_combo.start_addr_sub_high[i0].addr.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.start_addr_sub_high[i0].addr.value <= 32'h0;
            end else begin
                if(field_combo.start_addr_sub_high[i0].addr.load_next) begin
                    field_storage.start_addr_sub_high[i0].addr.value <= field_combo.start_addr_sub_high[i0].addr.next;
                end
            end
        end
        assign hwif_out.start_addr_sub_high[i0].addr.value = field_storage.start_addr_sub_high[i0].addr.value;
    end
    for(genvar i0=0; i0<16; i0++) begin
        // Field: axi_rt_regs.end_addr_sub_low[].addr
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.end_addr_sub_low[i0].addr.value;
            load_next_c = '0;
            if(decoded_reg_strb.end_addr_sub_low[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.end_addr_sub_low[i0].addr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.end_addr_sub_low[i0].addr.next = next_c;
            field_combo.end_addr_sub_low[i0].addr.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.end_addr_sub_low[i0].addr.value <= 32'h0;
            end else begin
                if(field_combo.end_addr_sub_low[i0].addr.load_next) begin
                    field_storage.end_addr_sub_low[i0].addr.value <= field_combo.end_addr_sub_low[i0].addr.next;
                end
            end
        end
        assign hwif_out.end_addr_sub_low[i0].addr.value = field_storage.end_addr_sub_low[i0].addr.value;
    end
    for(genvar i0=0; i0<16; i0++) begin
        // Field: axi_rt_regs.end_addr_sub_high[].addr
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.end_addr_sub_high[i0].addr.value;
            load_next_c = '0;
            if(decoded_reg_strb.end_addr_sub_high[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.end_addr_sub_high[i0].addr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.end_addr_sub_high[i0].addr.next = next_c;
            field_combo.end_addr_sub_high[i0].addr.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.end_addr_sub_high[i0].addr.value <= 32'h0;
            end else begin
                if(field_combo.end_addr_sub_high[i0].addr.load_next) begin
                    field_storage.end_addr_sub_high[i0].addr.value <= field_combo.end_addr_sub_high[i0].addr.next;
                end
            end
        end
        assign hwif_out.end_addr_sub_high[i0].addr.value = field_storage.end_addr_sub_high[i0].addr.value;
    end
    for(genvar i0=0; i0<16; i0++) begin
        // Field: axi_rt_regs.write_budget[].budget
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.write_budget[i0].budget.value;
            load_next_c = '0;
            if(decoded_reg_strb.write_budget[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.write_budget[i0].budget.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.write_budget[i0].budget.next = next_c;
            field_combo.write_budget[i0].budget.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.write_budget[i0].budget.value <= 32'h0;
            end else begin
                if(field_combo.write_budget[i0].budget.load_next) begin
                    field_storage.write_budget[i0].budget.value <= field_combo.write_budget[i0].budget.next;
                end
            end
        end
        assign hwif_out.write_budget[i0].budget.value = field_storage.write_budget[i0].budget.value;
    end
    for(genvar i0=0; i0<16; i0++) begin
        // Field: axi_rt_regs.read_budget[].budget
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.read_budget[i0].budget.value;
            load_next_c = '0;
            if(decoded_reg_strb.read_budget[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.read_budget[i0].budget.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.read_budget[i0].budget.next = next_c;
            field_combo.read_budget[i0].budget.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.read_budget[i0].budget.value <= 32'h0;
            end else begin
                if(field_combo.read_budget[i0].budget.load_next) begin
                    field_storage.read_budget[i0].budget.value <= field_combo.read_budget[i0].budget.next;
                end
            end
        end
        assign hwif_out.read_budget[i0].budget.value = field_storage.read_budget[i0].budget.value;
    end
    for(genvar i0=0; i0<16; i0++) begin
        // Field: axi_rt_regs.write_period[].period
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.write_period[i0].period.value;
            load_next_c = '0;
            if(decoded_reg_strb.write_period[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.write_period[i0].period.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.write_period[i0].period.next = next_c;
            field_combo.write_period[i0].period.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.write_period[i0].period.value <= 32'h0;
            end else begin
                if(field_combo.write_period[i0].period.load_next) begin
                    field_storage.write_period[i0].period.value <= field_combo.write_period[i0].period.next;
                end
            end
        end
        assign hwif_out.write_period[i0].period.value = field_storage.write_period[i0].period.value;
    end
    for(genvar i0=0; i0<16; i0++) begin
        // Field: axi_rt_regs.read_period[].period
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.read_period[i0].period.value;
            load_next_c = '0;
            if(decoded_reg_strb.read_period[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.read_period[i0].period.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.read_period[i0].period.next = next_c;
            field_combo.read_period[i0].period.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.read_period[i0].period.value <= 32'h0;
            end else begin
                if(field_combo.read_period[i0].period.load_next) begin
                    field_storage.read_period[i0].period.value <= field_combo.read_period[i0].period.next;
                end
            end
        end
        assign hwif_out.read_period[i0].period.value = field_storage.read_period[i0].period.value;
    end

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [10:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 11'h0) begin
            readback_data_var[31:0] = 32'h0;
        end
        if(rd_mux_addr == 11'h4) begin
            readback_data_var[31:0] = 32'h0;
        end
        if(rd_mux_addr == 11'h8) begin
            readback_data_var[31:0] = 32'h0;
        end
        for(int i0=0; i0<8; i0++) begin
            if(rd_mux_addr == 11'h2c + (11)'(i0) * 11'h4) begin
                readback_data_var[0] = hwif_in.rt_bypassed[i0].bypassed.next;
            end
        end
        for(int i0=0; i0<16; i0++) begin
            if(rd_mux_addr == 11'h2ac + (11)'(i0) * 11'h4) begin
                readback_data_var[31:0] = hwif_in.write_budget_left[i0].budget.next;
            end
        end
        for(int i0=0; i0<16; i0++) begin
            if(rd_mux_addr == 11'h2ec + (11)'(i0) * 11'h4) begin
                readback_data_var[31:0] = hwif_in.read_budget_left[i0].budget.next;
            end
        end
        for(int i0=0; i0<16; i0++) begin
            if(rd_mux_addr == 11'h32c + (11)'(i0) * 11'h4) begin
                readback_data_var[31:0] = hwif_in.write_period_left[i0].period.next;
            end
        end
        for(int i0=0; i0<16; i0++) begin
            if(rd_mux_addr == 11'h36c + (11)'(i0) * 11'h4) begin
                readback_data_var[31:0] = hwif_in.read_period_left[i0].period.next;
            end
        end
        for(int i0=0; i0<8; i0++) begin
            if(rd_mux_addr == 11'h3ac + (11)'(i0) * 11'h4) begin
                readback_data_var[0] = hwif_in.isolate[i0].isolate.next;
            end
        end
        for(int i0=0; i0<8; i0++) begin
            if(rd_mux_addr == 11'h3cc + (11)'(i0) * 11'h4) begin
                readback_data_var[0] = hwif_in.isolated[i0].isolated.next;
            end
        end
        if(rd_mux_addr == 11'h3ec) begin
            readback_data_var[31:0] = hwif_in.num_managers.num_managers.next;
        end
        if(rd_mux_addr == 11'h3f0) begin
            readback_data_var[31:0] = hwif_in.addr_width.addr_width.next;
        end
        if(rd_mux_addr == 11'h3f4) begin
            readback_data_var[31:0] = hwif_in.data_width.data_width.next;
        end
        if(rd_mux_addr == 11'h3f8) begin
            readback_data_var[31:0] = hwif_in.id_width.id_width.next;
        end
        if(rd_mux_addr == 11'h3fc) begin
            readback_data_var[31:0] = hwif_in.user_width.user_width.next;
        end
        if(rd_mux_addr == 11'h400) begin
            readback_data_var[31:0] = hwif_in.num_pending.num_pending.next;
        end
        if(rd_mux_addr == 11'h404) begin
            readback_data_var[31:0] = hwif_in.w_buffer_depth.w_buffer_depth.next;
        end
        if(rd_mux_addr == 11'h408) begin
            readback_data_var[31:0] = hwif_in.num_addr_regions.num_addr_regions.next;
        end
        if(rd_mux_addr == 11'h40c) begin
            readback_data_var[31:0] = hwif_in.period_width.period_width.next;
        end
        if(rd_mux_addr == 11'h410) begin
            readback_data_var[31:0] = hwif_in.budget_width.budget_width.next;
        end
        if(rd_mux_addr == 11'h414) begin
            readback_data_var[31:0] = 32'h8;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
