// Generated register defines for axi_tmu

// Copyright information found in source file:
// Copyright 2025 ETH Zurich and University of Bologna.

// Licensing information found in source file:
// Licensed under Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

#ifndef _AXI_TMU_REG_DEFS_
#define _AXI_TMU_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Register width
#define AXI_TMU_PARAM_REG_WIDTH 32

// time budget from awvld to awrdy
#define AXI_TMU_BUDGET_AWVLD_AWRDY_REG_OFFSET 0x0
#define AXI_TMU_BUDGET_AWVLD_AWRDY_BUDGET_AWVLD_AWRDY_MASK 0xff
#define AXI_TMU_BUDGET_AWVLD_AWRDY_BUDGET_AWVLD_AWRDY_OFFSET 0
#define AXI_TMU_BUDGET_AWVLD_AWRDY_BUDGET_AWVLD_AWRDY_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_BUDGET_AWVLD_AWRDY_BUDGET_AWVLD_AWRDY_MASK, .index = AXI_TMU_BUDGET_AWVLD_AWRDY_BUDGET_AWVLD_AWRDY_OFFSET })

// time budget from awhs to wfirst
#define AXI_TMU_BUDGET_AWHS_WFIRST_REG_OFFSET 0x4
#define AXI_TMU_BUDGET_AWHS_WFIRST_BUDGET_AWHS_WFIRST_MASK 0xff
#define AXI_TMU_BUDGET_AWHS_WFIRST_BUDGET_AWHS_WFIRST_OFFSET 0
#define AXI_TMU_BUDGET_AWHS_WFIRST_BUDGET_AWHS_WFIRST_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_BUDGET_AWHS_WFIRST_BUDGET_AWHS_WFIRST_MASK, .index = AXI_TMU_BUDGET_AWHS_WFIRST_BUDGET_AWHS_WFIRST_OFFSET })

// time budget from wvld to wrdy
#define AXI_TMU_BUDGET_WVLD_WRDY_REG_OFFSET 0x8
#define AXI_TMU_BUDGET_WVLD_WRDY_BUDGET_WVLD_WRDY_MASK 0xff
#define AXI_TMU_BUDGET_WVLD_WRDY_BUDGET_WVLD_WRDY_OFFSET 0
#define AXI_TMU_BUDGET_WVLD_WRDY_BUDGET_WVLD_WRDY_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_BUDGET_WVLD_WRDY_BUDGET_WVLD_WRDY_MASK, .index = AXI_TMU_BUDGET_WVLD_WRDY_BUDGET_WVLD_WRDY_OFFSET })

// time budget from one w beat to next
#define AXI_TMU_BUDGET_W_LIVENESS_REG_OFFSET 0xc
#define AXI_TMU_BUDGET_W_LIVENESS_BUDGET_W_LIVENESS_MASK 0xff
#define AXI_TMU_BUDGET_W_LIVENESS_BUDGET_W_LIVENESS_OFFSET 0
#define AXI_TMU_BUDGET_W_LIVENESS_BUDGET_W_LIVENESS_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_BUDGET_W_LIVENESS_BUDGET_W_LIVENESS_MASK, .index = AXI_TMU_BUDGET_W_LIVENESS_BUDGET_W_LIVENESS_OFFSET })

// time budget from wlast to bvld
#define AXI_TMU_BUDGET_WLAST_BVLD_REG_OFFSET 0x10
#define AXI_TMU_BUDGET_WLAST_BVLD_BUDGET_WLAST_BVLD_MASK 0xff
#define AXI_TMU_BUDGET_WLAST_BVLD_BUDGET_WLAST_BVLD_OFFSET 0
#define AXI_TMU_BUDGET_WLAST_BVLD_BUDGET_WLAST_BVLD_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_BUDGET_WLAST_BVLD_BUDGET_WLAST_BVLD_MASK, .index = AXI_TMU_BUDGET_WLAST_BVLD_BUDGET_WLAST_BVLD_OFFSET })

// time budget from bvld to brdy
#define AXI_TMU_BUDGET_BVLD_BRDY_REG_OFFSET 0x14
#define AXI_TMU_BUDGET_BVLD_BRDY_BUDGET_BVLD_BRDY_MASK 0xff
#define AXI_TMU_BUDGET_BVLD_BRDY_BUDGET_BVLD_BRDY_OFFSET 0
#define AXI_TMU_BUDGET_BVLD_BRDY_BUDGET_BVLD_BRDY_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_BUDGET_BVLD_BRDY_BUDGET_BVLD_BRDY_MASK, .index = AXI_TMU_BUDGET_BVLD_BRDY_BUDGET_BVLD_BRDY_OFFSET })

// time budget from arvld to arrdy
#define AXI_TMU_BUDGET_ARVLD_ARRDY_REG_OFFSET 0x18
#define AXI_TMU_BUDGET_ARVLD_ARRDY_BUDGET_ARVLD_ARRDY_MASK 0xff
#define AXI_TMU_BUDGET_ARVLD_ARRDY_BUDGET_ARVLD_ARRDY_OFFSET 0
#define AXI_TMU_BUDGET_ARVLD_ARRDY_BUDGET_ARVLD_ARRDY_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_BUDGET_ARVLD_ARRDY_BUDGET_ARVLD_ARRDY_MASK, .index = AXI_TMU_BUDGET_ARVLD_ARRDY_BUDGET_ARVLD_ARRDY_OFFSET })

// time budget from rvld to rrdy
#define AXI_TMU_BUDGET_RVLD_RRDY_REG_OFFSET 0x1c
#define AXI_TMU_BUDGET_RVLD_RRDY_BUDGET_RVLD_RRDY_MASK 0xff
#define AXI_TMU_BUDGET_RVLD_RRDY_BUDGET_RVLD_RRDY_OFFSET 0
#define AXI_TMU_BUDGET_RVLD_RRDY_BUDGET_RVLD_RRDY_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_BUDGET_RVLD_RRDY_BUDGET_RVLD_RRDY_MASK, .index = AXI_TMU_BUDGET_RVLD_RRDY_BUDGET_RVLD_RRDY_OFFSET })

// time budget from ar hs to rvalid first
#define AXI_TMU_BUDGET_ARHS_RFIRST_REG_OFFSET 0x20
#define AXI_TMU_BUDGET_ARHS_RFIRST_BUDGET_ARHS_RFIRST_MASK 0xff
#define AXI_TMU_BUDGET_ARHS_RFIRST_BUDGET_ARHS_RFIRST_OFFSET 0
#define AXI_TMU_BUDGET_ARHS_RFIRST_BUDGET_ARHS_RFIRST_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_BUDGET_ARHS_RFIRST_BUDGET_ARHS_RFIRST_MASK, .index = AXI_TMU_BUDGET_ARHS_RFIRST_BUDGET_ARHS_RFIRST_OFFSET })

// time budget from one r beat to next
#define AXI_TMU_BUDGET_R_LIVENESS_REG_OFFSET 0x24
#define AXI_TMU_BUDGET_R_LIVENESS_BUDGET_R_LIVENESS_MASK 0xff
#define AXI_TMU_BUDGET_R_LIVENESS_BUDGET_R_LIVENESS_OFFSET 0
#define AXI_TMU_BUDGET_R_LIVENESS_BUDGET_R_LIVENESS_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_BUDGET_R_LIVENESS_BUDGET_R_LIVENESS_MASK, .index = AXI_TMU_BUDGET_R_LIVENESS_BUDGET_R_LIVENESS_OFFSET })

// Is this subordinate device requested to be reset?
#define AXI_TMU_RESET_REG_OFFSET 0x28
#define AXI_TMU_RESET_RESET_BIT 0

// fault logs
#define AXI_TMU_FAULT_LOG_REG_OFFSET 0x2c
#define AXI_TMU_FAULT_LOG_FAULT_VALID_BIT 0
#define AXI_TMU_FAULT_LOG_FAULT_TYPE_MASK 0x7
#define AXI_TMU_FAULT_LOG_FAULT_TYPE_OFFSET 1
#define AXI_TMU_FAULT_LOG_FAULT_TYPE_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_FAULT_LOG_FAULT_TYPE_MASK, .index = AXI_TMU_FAULT_LOG_FAULT_TYPE_OFFSET })
#define AXI_TMU_FAULT_LOG_FAULT_DIR_BIT 4
#define AXI_TMU_FAULT_LOG_FAULT_PHASE_MASK 0xf
#define AXI_TMU_FAULT_LOG_FAULT_PHASE_OFFSET 5
#define AXI_TMU_FAULT_LOG_FAULT_PHASE_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_FAULT_LOG_FAULT_PHASE_MASK, .index = AXI_TMU_FAULT_LOG_FAULT_PHASE_OFFSET })
#define AXI_TMU_FAULT_LOG_FAULT_ID_MASK 0xffff
#define AXI_TMU_FAULT_LOG_FAULT_ID_OFFSET 9
#define AXI_TMU_FAULT_LOG_FAULT_ID_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_FAULT_LOG_FAULT_ID_MASK, .index = AXI_TMU_FAULT_LOG_FAULT_ID_OFFSET })

// latency from awvld to wfirst
#define AXI_TMU_LATENCY_AWVLD_WFIRST_REG_OFFSET 0x30
#define AXI_TMU_LATENCY_AWVLD_WFIRST_LATENCY_AWVLD_WFIRST_MASK 0x3ff
#define AXI_TMU_LATENCY_AWVLD_WFIRST_LATENCY_AWVLD_WFIRST_OFFSET 0
#define AXI_TMU_LATENCY_AWVLD_WFIRST_LATENCY_AWVLD_WFIRST_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_LATENCY_AWVLD_WFIRST_LATENCY_AWVLD_WFIRST_MASK, .index = AXI_TMU_LATENCY_AWVLD_WFIRST_LATENCY_AWVLD_WFIRST_OFFSET })

// latency from wvld to wrdy
#define AXI_TMU_LATENCY_WVLD_WRDY_REG_OFFSET 0x34
#define AXI_TMU_LATENCY_WVLD_WRDY_LATENCY_WVLD_WRDY_MASK 0x3ff
#define AXI_TMU_LATENCY_WVLD_WRDY_LATENCY_WVLD_WRDY_OFFSET 0
#define AXI_TMU_LATENCY_WVLD_WRDY_LATENCY_WVLD_WRDY_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_LATENCY_WVLD_WRDY_LATENCY_WVLD_WRDY_MASK, .index = AXI_TMU_LATENCY_WVLD_WRDY_LATENCY_WVLD_WRDY_OFFSET })

// latency from wvld to wlast
#define AXI_TMU_LATENCY_WVLD_WLAST_REG_OFFSET 0x38
#define AXI_TMU_LATENCY_WVLD_WLAST_LATENCY_WVLD_WLAST_MASK 0x3ff
#define AXI_TMU_LATENCY_WVLD_WLAST_LATENCY_WVLD_WLAST_OFFSET 0
#define AXI_TMU_LATENCY_WVLD_WLAST_LATENCY_WVLD_WLAST_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_LATENCY_WVLD_WLAST_LATENCY_WVLD_WLAST_MASK, .index = AXI_TMU_LATENCY_WVLD_WLAST_LATENCY_WVLD_WLAST_OFFSET })

// latency from wlast to bvld
#define AXI_TMU_LATENCY_WLAST_BVLD_REG_OFFSET 0x3c
#define AXI_TMU_LATENCY_WLAST_BVLD_LATENCY_WLAST_BVLD_MASK 0x3ff
#define AXI_TMU_LATENCY_WLAST_BVLD_LATENCY_WLAST_BVLD_OFFSET 0
#define AXI_TMU_LATENCY_WLAST_BVLD_LATENCY_WLAST_BVLD_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_LATENCY_WLAST_BVLD_LATENCY_WLAST_BVLD_MASK, .index = AXI_TMU_LATENCY_WLAST_BVLD_LATENCY_WLAST_BVLD_OFFSET })

// latency from bvld to brdy
#define AXI_TMU_LATENCY_BVLD_BRDY_REG_OFFSET 0x40
#define AXI_TMU_LATENCY_BVLD_BRDY_LATENCY_BVLD_BRDY_MASK 0x3ff
#define AXI_TMU_LATENCY_BVLD_BRDY_LATENCY_BVLD_BRDY_OFFSET 0
#define AXI_TMU_LATENCY_BVLD_BRDY_LATENCY_BVLD_BRDY_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_LATENCY_BVLD_BRDY_LATENCY_BVLD_BRDY_MASK, .index = AXI_TMU_LATENCY_BVLD_BRDY_LATENCY_BVLD_BRDY_OFFSET })

// latency from arvld to arrdy
#define AXI_TMU_LATENCY_ARVLD_ARRDY_REG_OFFSET 0x44
#define AXI_TMU_LATENCY_ARVLD_ARRDY_LATENCY_ARVLD_ARRDY_MASK 0x3ff
#define AXI_TMU_LATENCY_ARVLD_ARRDY_LATENCY_ARVLD_ARRDY_OFFSET 0
#define AXI_TMU_LATENCY_ARVLD_ARRDY_LATENCY_ARVLD_ARRDY_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_LATENCY_ARVLD_ARRDY_LATENCY_ARVLD_ARRDY_MASK, .index = AXI_TMU_LATENCY_ARVLD_ARRDY_LATENCY_ARVLD_ARRDY_OFFSET })

// latency from arvld to rvld
#define AXI_TMU_LATENCY_ARVLD_RVLD_REG_OFFSET 0x48
#define AXI_TMU_LATENCY_ARVLD_RVLD_LATENCY_ARVLD_RVLD_MASK 0x3ff
#define AXI_TMU_LATENCY_ARVLD_RVLD_LATENCY_ARVLD_RVLD_OFFSET 0
#define AXI_TMU_LATENCY_ARVLD_RVLD_LATENCY_ARVLD_RVLD_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_LATENCY_ARVLD_RVLD_LATENCY_ARVLD_RVLD_MASK, .index = AXI_TMU_LATENCY_ARVLD_RVLD_LATENCY_ARVLD_RVLD_OFFSET })

// latency from rvld to rrdy
#define AXI_TMU_LATENCY_RVLD_RRDY_REG_OFFSET 0x4c
#define AXI_TMU_LATENCY_RVLD_RRDY_LATENCY_RVLD_RRDY_MASK 0x3ff
#define AXI_TMU_LATENCY_RVLD_RRDY_LATENCY_RVLD_RRDY_OFFSET 0
#define AXI_TMU_LATENCY_RVLD_RRDY_LATENCY_RVLD_RRDY_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_LATENCY_RVLD_RRDY_LATENCY_RVLD_RRDY_MASK, .index = AXI_TMU_LATENCY_RVLD_RRDY_LATENCY_RVLD_RRDY_OFFSET })

// latency from rvld to rlast
#define AXI_TMU_LATENCY_RVLD_RLAST_REG_OFFSET 0x50
#define AXI_TMU_LATENCY_RVLD_RLAST_LATENCY_RVLD_RLAST_MASK 0x3ff
#define AXI_TMU_LATENCY_RVLD_RLAST_LATENCY_RVLD_RLAST_OFFSET 0
#define AXI_TMU_LATENCY_RVLD_RLAST_LATENCY_RVLD_RLAST_FIELD \
  ((bitfield_field32_t) { .mask = AXI_TMU_LATENCY_RVLD_RLAST_LATENCY_RVLD_RLAST_MASK, .index = AXI_TMU_LATENCY_RVLD_RLAST_LATENCY_RVLD_RLAST_OFFSET })

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _AXI_TMU_REG_DEFS_
// End generated register defines for axi_tmu